= AWS Technical Essentials

== Introducing AWS Amazon Web Services

Cloud computing is the on-demand delivery of IT resources over the internet with pay-as-you-go pricing.
We’ll need to use these AWS services to architect a scalable, highly available, and cost effective infrastructure to host our application. 
 There are the six main advantages to running your workloads on AWS.
Pay as you go
Benefit from massive economies of scale.
Stop guessing capacity
Increase speed and agility
Stop spending money running and maintaining data centers
Stop spending money running and maintaining data centers
Go global in minutes.

https://aws.amazon.com/what-is-cloud-computing/
http://docs.aws.amazon.com/whitepapers/latest/aws-overview/types-of-cloud-computing.html
https://aws.amazon.com/what-is-aws/

Availability Zones or AZ are clusters of datacenters.An AZ consists of one or more data centers with redundant power, networking, and connectivity. 
Region are cluster of AZ

As a basic rule, there are four aspects you need to consider
when deciding which AWS region to use:
compliance, latency, price, and service availability. 

Latency is all about about how close your IT resources are
to your user base. 

AWS Regions are independent from one another. This means that your data is not replicated from one Region to another, without your explicit consent and authorization.

Latency. If your application is sensitive to latency, choose a Region that is close to your user base. This helps prevent long wait times for your customers. Synchronous applications such as gaming, telephony, WebSockets, and IoT are significantly affected by higher latency, but even asynchronous workloads, such as ecommerce applications, can suffer from an impact on user connectivity.
 
Price. Due to the local economy and the physical nature of operating data centers, prices may vary from one Region to another. The pricing in a Region can be impacted by internet connectivity, prices of imported pieces of equipment, customs, real estate, and more. Instead of charging a flat rate worldwide, AWS charges based on the financial factors specific to the location.  
 
Service availability. Some services may not be available in some Regions. The AWS documentation provides a table containing the Regions and the available services within each one.
 
Data compliance. Enterprise companies often need to comply with regulations that require customer data to be stored in a specific geographic territory. If applicable, you should choose a Region that meets your compliance requirements.

Maintain Resiliency

To keep your application available, you need to maintain high availability and resiliency. A well-known best practice for cloud architecture is to use Region-scoped, managed services.
When that is not possible, make sure the workload is replicated across multiple AZs. At a minimum, you should use two AZs. If one entire AZ fails, your application will have infrastructure up and running in at least a second AZ to take over the traffic.

https://aws.amazon.com/about-aws/global-infrastructure/
https://docs.aws.amazon.com/whitepapers/latest/aws-overview/global-infrastructure.html
https://aws.amazon.com/about-aws/global-infrastructure/regions_az/
https://docs.aws.amazon.com/general/latest/gr/rande.html
https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

You can make these API calls in several ways
but the three main ways we're going to talk about
are the AWS Management Console,
the AWS Command Line Interface
and the AWS Software Development Kits or SDKs. 

Working with AWS API
https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/getting-started.html
https://aws.amazon.com/cli/
https://aws.amazon.com/es/developer/tools/










the new product feature’s time-to-market is increasing 
