= C# Notes 
:toc: auto


== Members
Fields denote storage locations, properties has accessors (get set)

https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks#members

== Guidelines 
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/

== Accessibility 

* public: Access isn't limited.
* private: Access is limited to this class.
* protected: Access is limited to this class or classes derived from this class.
* internal: Access is limited to the current assembly (.exe or .dll).
* protected internal: Access is limited to this class, classes derived from this class, or classes within the  same assembly.
* private protected: Access is limited to this class or classes derived from this type within the same assembly.

== Operators
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/

* String.Contains
* String.ToUpper, ToLower, Replace
* string.Empty; initialize a var with a empty string
* Use tuple for swap values in array (array[i - 1], array[i]) = (array[i], array[i - 1])

* Arrays,Collections use IEnumerable<T> interface
* Hashtable: https://www.tutorialspoint.com/csharp/csharp_hashtable.htm

* Delegates (https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/features#delegates-and-lambda-expressions)
https://code-maze.com/csharp-delegates/: 
* syntax delegate double Function(double x);
* nameof() generate the name of its operand.

C# has the two built-in delegates: Func<T> and Action<T>
----
    Func<T> Syntax: 
        Func<Type1, Type2..., ReturnType> DelegateName = new Func<Type1, Type2..., ReturnType>(MethodName); or
        Func< Type1, Type2..., ReturnType> name = MethodName;
    Action<T>
        Action<Type1, Type2...> DelegateName = new Action<Type1, Type2...>(MethodName);
        Action < Type1, Type2...> DelegateName = MethodName;
----
== Define an access level to variables
* static keyword are class variables or non-instance variable
* readonly keyword like instance variables but cannot be modified, the value is assign in the constructor
* protected functions can be called only in derived classes

== Program structure

https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/

== Files and Registry 
(https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/)

* File system information in the following classes:
** System.IO.FileInfo, 
** System.IO.DirectoryInfo, 
** System.IO.DriveInfo, 
** System.IO.Directory
** System.IO.File   

+
.Example
[source,csharp]
----
System.IO.DriveInfo di = new System.IO.DriveInfo(@"C:\");
----
* Methods
** System.Environment.GetLogicalDrives

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-get-information-about-files-folders-and-drives

** GetFiles
** GetDirectories
+
NOTE: If any one of the subdirectories under the specified root causes a *DirectoryNotFoundException* or *UnauthorizedAccessException*, the whole method fails and returns no directories. 

=== Notes    

    Traverse directory tree manually    
        pre-order traversal : files first
        post-order traversal : subdirectories first
        You can use recursion or stack-based traversal

        Recursion:
            Can cause a stack overflow exception if the dir tree is deeply nested and large
            Example: #recursive_traverse_directory_tree

        No recursion:
        Uses generic Stack<T> collection type which is LIFO stack
        Example: #no_recursion_traverse_dirtree

        If you must store the contents of a directory tree, either in memory or 
        on disk, the best option is to store only the FullName property 
        (of type string) for each file. You can then use this string to create 
        a new FileInfo or DirectoryInfo object as necessary, or open any file 
        that requires additional processing.

        When you process user-specified path strings, you should also handle 
        exceptions for the following conditions:
            The file name is malformed. For example, it contains invalid characters 
                    or only white space.
            The file name is null.
            The file name is longer than the system-defined maximum length.
            The file name contains a colon (:).

== Pattern Matching (https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/pattern-matching)
    Declarative pattern if(maybe is int number)
                            Console.WriteLine($"Maybe is int equal to {number}");
    switch expression
        Syntax: variable switch { expression => return_value,
                                    { } matches a non-null object that did'nt match an earlier arm
                                    null matches null values}
        You must match all kind of expressions, if not, compiler issues a warning

    Pattern matching makes some types of code more readable and offers an alternative to object-oriented techniques 
    when you can't add code to your classes. The cloud is causing data and functionality to live apart. 
    The shape of the data and the operations on it aren't necessarily described together. 
    In this tutorial, you consumed existing data in entirely different ways from its original function. 
    Pattern matching gave you the ability to write functionality that overrode those types, even though you couldn't extend them.

StreamReader and StreamWriter

== Comments

Use /// three slashes to generate comments. See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments[Documentation comments]

== editorconfig
You can use a .editorconfig file to ensure consistent formatting. See https://learn.microsoft.com/es-es/dotnet/fundamentals/code-analysis/code-style-rule-options[Code-style rule options]

== Unit test 
https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test:
[source,bash]
----
    dotnet new sln -o <solution_folder>  #Create a new solution.

    dotnet new classlib -o <class_library_folder> 

    dotnet sln add <route-csproj> #add the class library project to the solution.

    dotnet new xunit -o PrimeService.Tests  #Create the test project

    dotnet sln add ./PrimeService.Tests/PrimeService.Tests.csproj   #Add the test project to the solution file.

    dotnet add <tests_folder/csproj-file> reference <folder-source/csproj-file>  #Add the PrimeService class library as a dependency to the PrimeService.Tests project.
----

Name the test: public class ReferenceClass_thingToBeTested

Use ARRANGE,ACTION,ASSERT

== Health Checks

In the Net Core ecosystem, background services are called Hosted services because 
a single host can run multiple of these services. This services implement the 
`IHostedService` interface.
We can leverage the `BackgroundService` abstract class for this purpose.

implement IHealthCheck 
Patterns: Really depends on how you monitor your app, examples are touching a file 
    or configuring an endpoint in the app. 

    https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-8.0
    https://dev.to/isaacojeda/implementacion-de-health-checks-en-aspnet-core-3a01
    https://dzone.com/articles/monitoring-health-of-aspnet-core-background-servic

== Running scripts with C#

Use the class `Process` in the System.Diagnostics namespace.

.Example
[source,csharp]
----
    var scriptArguments = "-ExecutionPolicy Bypass -File \""+pathToScript+"\"";
    var processStartInfo = new ProcessStartInfo("powershell.exe",scriptArguments);
    processStartInfo.RedirectStandardOutput = true;
    processStartInfo.RedirectStandardError = true;

    using var process = new Process();
    process.StartInfo = processStartInfo;
    process.Start();
    string output = process.StandardOutput.ReadToEnd();
    string error = process.StandardError.ReadToEnd();
    Console.WriteLine(output);
----