= Zabbix
:source-highlighter: highlight.js
//:highlightjs-languages: powershell
:author: Alberto Ramirez
:revdate: {localdate}
:revnumber: 1.0.0
:toc:

== Database Size

.The table contains formulas that can be used to calculate the disk space required for Zabbix system:
[col="1,1"]
|===
|Parameter 	|Formula for required disk space (in bytes)

|Zabbix configuration 	
|Fixed size. Normally 10MB or less.

|History 	
|days*(items/refresh rate)*24*3600*bytes

* items : number of items
* days : number of days to keep history
* refresh rate : average refresh rate of items

bytes : number of bytes required to keep single value, depends on database engine, normally ~90 bytes.

|Trends 	
|days*(items/3600)*24*3600*bytes
items : number of items
days : number of days to keep history
bytes : number of bytes required to keep single trend, depends on the database engine, normally ~90 bytes.

|Events 	
|days*events*24*3600*bytes
events : number of event per second. One (1) event per second in worst-case scenario.
days : number of days to keep history
bytes : number of bytes required to keep single trend, depends on the database engine, normally 
~330 + average number of tags per event * 100 bytes.
|===

So, the total required disk space can be calculated as:
Configuration + History + Trends + Events
The disk space will NOT be used immediately after Zabbix installation. Database size will grow then it will stop growing at some point, which depends on housekeeper settings.

https://www.zabbix.com/documentation/current/en/manual/installation/requirements#database-size

== Using templates

=== Best practices

https://www.zabbix.com/documentation/guidelines/en/thosts/best_practices

=== Naming templates

Name the templates in a significant way, think of linking a template as assigning roles or applications to your hosts. Bad examples are:

* Template for checking web connectivity
* SAN
* Ping webserver

=== Community Templates 

https://www.zabbix.com/integrations[Official Integrations Page]


== Reducing pulling and server overhead when collect metrics

https://zabbix.tips/reduce-polling-with-dependent-items-and-jsonpath/[Reducing pulling and server overhead when collect metrics]


== Network Discovery

You can discover devices on your network and add them to zabbix for monitoring. Go to *Data Collection* -> *Discovery* and add or modify the rule accordingly.
By default the rule check for zabbix agents in the network and is disabled.

Now, go to *Monitoring* -> *Discovery* and view the list of discovered devices in your network. If it isn't populated, try restarting the server.

== Zabbix agent

Check linux version host RPM based: cat /etc/*rel* or hostnamectl

https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_agent2[Zabbix agent 2 (UNIX)]

https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_agent2_win[Zabbix agent 2 (Windows)]

https://www.zabbix.com/documentation/current/en/manual/appendix/protocols/zabbix_agent2[Zabbix agent 2 protocol]

https://www.zabbix.com/documentation/current/en/manual/guides/monitor_windowsMonitor[Windows with Zabbix agent Quickstart]

https://www.zabbix.com/documentation/current/en/manual/appendix/items/win_permissions[Minimum permission level for Windows agent items]

https://www.zabbix.com/documentation/current/en/manual/guides/monitor_linux[Monitor Linux with Zabbix agent]

https://www.zabbix.com/documentation/current/en/manual/appendix/install/windows_agent[Zabbix agent on Microsoft Windows]

https://www.zabbix.com/download?zabbix=6.4&os_distribution=red_hat_enterprise_linux&os_version=9&components=agent_2&db=&ws=[Download and install Zabbix Agent2 RHEL9]

https://poweradm.com/install-zabbix-agent/[Zabbix: Agent Installation on Linux (Personal Blog)]

=== Restricting agent checks

When restricting agent checks is recommended to allow specific checks and deny others:

.Whitelist specific checks with AllowKey parameters, deny others with DenyKey=*
----
# Allow reading logs: 
AllowKey=vfs.file.*[/var/log/*] 

# Allow localtime checks 
AllowKey=system.localtime[*] 

# Deny all other keys 
DenyKey=*
---- 

.Patterns
* AllowKey=<pattern> - which checks are allowed; <pattern> is specified using a wildcard (*) expression
* DenyKey=<pattern> - which checks are denied; <pattern> is specified using a wildcard (*) expression

NOTE: All system.run[*] items (remote commands, scripts) are disabled by default

https://www.zabbix.com/documentation/current/en/manual/config/items/restrict_checks[Zabbix Docs]


=== Best practices 

https://www.zabbix.com/documentation/current/en/manual/installation/requirements/best_practices[Best practices for secure Zabbix setup]

https://www.zabbix.com/security_advisories#modal[Zabbix Security Advisories and CVE database]

https://www.zabbix.com/forum/zabbix-cookbook/17295-best-practices-of-monitoring-in-medium-large-enviroments/page2[2010 Azabbix blog]

=== Access control
*Principle of least privilege*

The principle of least privilege should be used at all times for Zabbix. This principle means that user accounts at all times should run with as few privileges as possible.

Giving extra permissions to 'zabbix' user will allow it to access configuration files and execute operations that can compromise the overall security of the infrastructure.

In the default configuration, Zabbix server and Zabbix agent processes share one 'zabbix' user. If you wish to make sure that the agent cannot access sensitive details in server configuration (e.g. database login information), the agent should be run as a different user:

. Create a secure user
. Specify this user in the agent configuration file ('User' parameter)
. Restart the agent with administrator privileges. Privileges will be dropped to the specified user.

*Revoke write access to SSL configuration file in Windows*

Zabbix Windows agent compiled with OpenSSL will try to reach the SSL configuration file in c:\openssl-64bit. The "openssl-64bit" directory on disk C: can be created by non-privileged users.

So for security hardening, it is required to create this directory manually and revoke write access from non-admin users.


////
Requirement: I was trying to fetch data for "CPU system time" and "Available memory" in one query.
Behavior : Data was returned either for CPU or Memory but not for both in one query.
Fact : Data type for CPU and Memory are different and "history" parameter in "history.get" method doesn't support multiple values.
resolution : supplied data type of metric (variable replacement) in query using "value_type" for metric in question.
history => value_type

This resolve the issue of getting data for some metrics only.

2-
Requirement : Trying to fetch performance data for all hosts.
Behavior : Data was returned for some hosts only.
Fact : Some metrics data was collected every minute and some metrics data was collected for every five minutes.
Resolution : Check the polling interval for all metrics in question.
////


